name: bide_et_musique
description: Ecouter et gerer son compte bide et musique

version: 1.3.4+11

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  html:
  xml:
  cupertino_icons: ^0.1.2
  flutter_radio: ^0.1.5
  flutter_html: ^0.9.8
  url_launcher: ^5.0.2
  share: 0.6.1+1
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vinyl_record.png