name: bide_et_musique
description: Ecouter et gerer son compte bide et musique

version: 2.3.0+17

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  html: ^0.14.0
  xml:
  cupertino_icons: ^0.1.2
  audio_service: ^0.3.0
  flutter_radio: ^0.1.7
  flutter_html: ^0.10.3
  url_launcher: ^5.0.3
  share: ^0.6.1
  shared_preferences: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bm_logo.png