name: bide_et_musique
description: Ecouter et gerer son compte bide et musique

version: 2.3.6+23

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+3
  xml: ^3.5.0
  audio_service: ^0.4.1
  flutter_radio: ^0.1.7
  flutter_html: ^0.11.0
  url_launcher: ^5.2.3
  share: ^0.6.2+4
  shared_preferences: ^0.5.3+5
  uni_links: ^0.2.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bm_logo.png