name: bide_et_musique
description: Écouter et consulter la web radio 'Bide et Musique'

version: 3.2.1+38

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  html: ^0.14.0+3
  xml: ^3.3.1
  audio_service: ^0.8.0
  just_audio: ^0.1.8
  flutter_html: ^1.0.0
  url_launcher: ^5.4.7
  share: ^0.6.4+2
  shared_preferences: ^0.5.7+2
  uni_links: ^0.4.0
  diacritic: ^0.1.1
  cached_network_image: ^2.2.0+1
  page_indicator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg