name: bide_et_musique
description: Écouter et consulter la web radio 'Bide et Musique'

version: 3.3.0+39

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  html: ^0.14.0+3
  xml: ^4.2.0
  audio_service: ^0.11.2
  just_audio: ^0.2.2
  flutter_html: ^0.11.1
  url_launcher: ^5.4.11
  share: ^0.6.4+3
  shared_preferences: ^0.5.7+3
  uni_links: ^0.4.0
  diacritic: ^0.1.1
  cached_network_image: ^2.2.0+1
  page_indicator: ^0.3.0
  package_info: ^0.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png