name: bide_et_musique
description: Ecouter et gerer son compte bide et musique

version: 2.0.0+14

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  html:
  xml:
  cupertino_icons: ^0.1.2
  audio_service: ^0.2.0
  flutter_radio: ^0.1.5
  flutter_html: ^0.10.1
  url_launcher: ^5.0.2
  share: ^0.6.1+1
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bm_logo.png