name: bide_et_musique
description: Ecouter et consulter la web radio 'Bide et Musique'

version: 2.3.8+25

environment:
  sdk: '>=2.6.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  html: ^0.14.0+3
  xml: ^3.5.0
  audio_service: ^0.5.6
  flutter_radio: ^0.1.7
  flutter_html: ^0.11.1
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  uni_links: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/bm_logo.png