name: bide_et_musique
description: Écouter et consulter la web radio 'Bide et Musique'

version: 3.2.0+37

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  html: ^0.14.0+3
  xml: ^4.1.0
  audio_service: ^0.7.2
  just_audio: ^0.1.7
  flutter_html: ^0.11.1
  url_launcher: ^5.4.5
  share: ^0.6.4
  shared_preferences: ^0.5.7
  uni_links: ^0.2.0
  diacritic: ^0.1.1
  cached_network_image: ^2.1.0+1
  page_indicator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg