name: bide_et_musique
description: Écouter et consulter la web radio 'Bide et Musique'

version: 2.4.3+29

environment:
  sdk: '>=2.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  html: ^0.14.0+3
  xml: ^3.7.0
  audio_service: ^0.5.7
  just_audio: ^0.0.6
  flutter_html: ^0.11.1
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  uni_links: ^0.2.0
  diacritic: ^0.1.1
  cached_network_image: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bandeau.png
    - assets/bm_logo.png
    - assets/bm_logo_white.png
    - assets/vinyl-default.jpg